from deque import Deque

deque = Deque()

print("===== addFirst =====")
print("isEmpty : ", deque.is_empty())
deque.add_first(1)
deque.add_first(2)
deque.add_first(3)
deque.add_first(4)
deque.add_first(5)
deque.print_all()
print("isEmpty : ", deque.is_empty())
print("\n")

print("===== removeFirst =====")
deque.remove_first()
deque.print_all()
deque.remove_first()
deque.print_all()
deque.remove_first()
deque.print_all()
deque.remove_first()
deque.print_all()
deque.remove_first()
deque.print_all()

print("isEmpty : ", deque.is_empty())
print("\n")

print("===== addLast =====")
deque.add_last(1)
deque.add_last(2)
deque.add_last(3)
deque.add_last(4)
deque.add_last(5)
deque.print_all()
print("isEmpty : ", deque.is_empty())
print("\n")

print("===== removeLast =====")
deque.remove_last()
deque.print_all()
deque.remove_last()
deque.print_all()
deque.remove_last()
deque.print_all()
deque.remove_last()
deque.print_all()
deque.remove_last()
deque.print_all()
print("isEmpty : ", deque.is_empty())

